# Generated by Django 5.2.6 on 2025-09-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('credentials', models.JSONField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('picture', models.URLField(blank=True, default='')),
            ],
        ),
    ]
