# Generated by Django 5.2.6 on 2025-10-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_classroom_course_assignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('task', 'channel', 'notify_at'), name='uq_reminder_task_channel_when'),
        ),
    ]
