# Generated by Django 5.2.6 on 2025-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reminder_uq_reminder_task_channel_when'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='uq_reminder_task_channel_when',
        ),
        migrations.AddField(
            model_name='reminder',
            name='days_before',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['task', 'notify_at'], name='core_remind_task_id_f9bb02_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(fields=('task', 'days_before'), name='uq_reminder_task_days_before'),
        ),
    ]
