# Generated by Django 5.2.6 on 2025-10-22 XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_reminder_uq_reminder_task_channel_when_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminder',
            name='uq_reminder_task_days_before',
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='core_remind_task_id_f9bb02_idx',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='days_before',
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.UniqueConstraint(
                fields=('task', 'channel', 'notify_at'),
                name='uq_reminder_task_channel_time',
            ),
        ),
    ]
