# Generated by Django 5.2.6 on 2025-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_reminder_uq_reminder_task_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='classroom_alt_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='classroom_course_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='classroom_work_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='color_tag',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='course_name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='task',
            name='is_classroom_linked',
            field=models.BooleanField(default=False),
        ),
    ]
