# Generated by Django 5.2.6 on 2025-11-03 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_classroom_alt_link_task_classroom_course_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='idx_tasks_subject_due',
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source', 'external_id'], name='core_task_source_330865_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['classroom_course_id', 'classroom_work_id'], name='core_task_classro_1b7ec6_idx'),
        ),
    ]
