# Generated by Django 5.2.6 on 2025-11-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_task_idx_tasks_subject_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('-', 'None'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='-', max_length=20),
        ),
    ]
