# Generated by Django 5.2.6 on 2025-11-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_classro_1b7ec6_idx',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='classroom_alt_link',
            new_name='assignment_alt_link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='classroom_course_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='classroom_work_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='color_tag',
        ),
        migrations.RemoveField(
            model_name='task',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_classroom_linked',
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='none', max_length=20),
        ),
    ]
