# Generated by Django 5.2.6 on 2025-11-04 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_task_core_task_classro_1b7ec6_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='classroom_assignment_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['classroom_assignment_id'], name='core_task_classro_0bb625_idx'),
        ),
    ]
