# Generated by Django 5.2.6 on 2025-11-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_task_classroom_assignment_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='core_task_classro_0bb625_idx',
        ),
        migrations.RemoveField(
            model_name='task',
            name='classroom_assignment_id',
        ),
    ]
