# Generated by Django 5.2.6 on 2025-11-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_task_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_days_before',
            field=models.IntegerField(default=3),
        ),
    ]
